### ISSUE TITLE
best practice: afbakening zonneakker, zonnepanelen op veld

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#10]
Zonneakker, zonnepanelen, veld met zonnepanelen
Hoe moeten we een zonneakker opnemen in de BGT?

In de BGT (verplicht) en in IMGeo (optioneel) zijn hier geen mogelijkheden voor. Wel kan in IMGeo een Functioneel Gebied worden opgenomen, dat in eigen beheer (BOR applicatie) als zonnepaneelveld/zonneakker kan worden geclassificeerd. Het Functioneel Gebied kan in de BGT landelijk worden uitgewisseld zonder nadere classificatie.

IMGeo heeft geen eigen classificatie om een zonnepaneelveld op te nemen. Voor de doorontwikkeling van IMGeo hadden we destijds een uitbreiding van de classificaties van Functioneel Gebied in beeld, met het type ‘zonnepaneelveld’, maar dat voorstel heeft  het op verzoek van bronhouders i.v.m. technische impact niet gehaald.
Het is wel mogelijk binnen IMGeo om dit veld als FunctioneelGebied af te bakenen, met een bgt-type ‘niet-bgt’ en plus-type ‘geenWaarde’ of leeg, en in de eigen (beheer)registratie een nadere classificatie op te nemen.

Dit object FunctioneelGebied kan zonder nadere classificatie met de LV-BGT worden uitgewisseld.

**Comment by SilvyGEONOVUM** [comment]
_zou je er niet beter een (of meer) puntobject(en) van objecttype Installatie met attribuut Type Zonnepaneel van maken?_

**Comment by adbgnm** [comment]
Opnemen in FAQ + toevoegen foto aan Functioneel Gebied.

**Comment by adbgnm** [comment]
Zou een zonneakker te scharen zijn onder Functioneel Gebied > maatschappelijke en/of publieksvoorziening?

**Comment by SilvyGEONOVUM** [comment]
## **Hoe baken ik een terrein af met zonnepanelen (zonneakker) in de BGT?**
In de gegevenscatalogi (BGT en Imgeo) zijn geen classificatie opgenomen om een terrein te benoemen als zonneakker. Wel is er de mogelijkheid om een los zonnepaneel op te nemen. In het kader van de energietransitie is het gewenst om deze terreinen met zonnepanelen te onderscheiden.

Het advies is om het terrein af te bakenen als een IMGeo objecttype FunctioneelGebied, zonder verdere classificatie. Daarnaast kan bv op de hoekpunten van het terrein een zonnepaneel opgevoerd worden, door het opvoeren van het IMGeo objecttype Installatie van het type Zonnepaneel. Door deze combinatie, functioneel gebied en zonnepaneel, kan een gebruiker van de BGT een zonneakker opzoeken.
In de beheeromgeving kan hier een nadere classificatie (bijvoorbeeld 'zonneakker') aan worden toegevoegd.

Voorbeeld
{foto}

**Comment by SilvyGEONOVUM** [comment]
nav opmerkingen van beoordelingsgroepje:
In onze gemeente trof ik het volgende aan :
- Afdak van zonnepanelen op een openbare parkeerplaats
![image](https://user-images.githubusercontent.com/62252105/216596282-a03662b3-6f31-4ebd-b2a1-28dda7717c0d.png)

en Afdak van zonnepanelen boven een erf van een autobedrijf
![image](https://user-images.githubusercontent.com/62252105/216596365-72d97be1-3910-4c6f-ab8b-0b33d47a6cd2.png)

Deze worden nu op niveau +1 als Overig Bouwwerk, overkapping vastgelegd. Is dit wenselijk ?<

**Comment by SilvyGEONOVUM** [comment]
nog meer commentaar:
De afbeelding in het  objectenhandboek is er een die je bijvoorbeeld langs de weg of in een weiland ziet gecombineerd met een paal. Maar meestal liggen ze op daken. Eigenlijk zijn ze altijd verbonden (letterlijk in de zin van vastgemaakt) met een ander object, zoals pand, overkapping, grasland en zelfs water. En vaak zijn het er meer dan 1. 

Hoe hier mee om te gaan? Voor elk zonnepaneel een puntje, is niet te doen, want ik weet dat bedrijven die dit met remote sensing inwinnen dit ook niet altijd doen. Die kijken meestal naar een groep aaneengeschakelde panelen en karteren daar 1 punt, en geven soms aan hoeveel panelen het betreft. Wij als gemeente willen meestal weten hoeveel panelen we hebben op de daken. 

Waarom niet een nieuw functioneel gebied: zonnepanelenweide (of -park) toevoegen? Kunnen we het onderdeel functionele gebieden van de BGT niet wat meer een levend onderdeel laten zijn en niet zo behandelen als een opdelende en de inrichtende objecten? Een uitbreiding van functionele gebieden zal elke bronhouder toejuichen, lijkt mij, De geel gearceerde vind ik geen goede oplossing als je dit doet en je maakt een selectie op zonnepanelen krijg je niet een goed resultaat. Dus dan maar een functioneel gebied zonder nadere aanduiding… Ik zou een zonnepark met 1 punt aanduiden (installatie > zonnepaneel).  Dan zijn er in een achterliggende registratie binnen de gemeente attributen te koppelen waardoor je een zonnepark kan onderscheiden van een heleboel panelen op een plat dak. 

![zonnepark](https://user-images.githubusercontent.com/62252105/219316946-f83797e4-ef0a-486d-a859-077b02f587fa.jpg)


Hoi henk-jan
Dank voor je input.
Het was me nog niet helemaal duidelijk wat je voorstel is met de zonneakkers of zonnepark :
-Vind je alleen een functioneel gebied zonder nadere classificatie voldoende?
-Of wil je dat functioneel gebied zonder nadere classificatie en er alsnog 1 zonnepaneel (installatie > zonnepaneel)? (ipv 4 op de hoekpunten)
-of was het alleen 1 zonnepaneel (dus geen functioneel gebied erbij)

Je voorstel om een classificatie ‘zonnepark’ toe te voegen aan functionele gebieden, dat zou natuurlijk nog beter zijn, maar die is er nog niet. We nemen je wens mee naar de wijzigingsverzoeken voor een nieuwe versie van imgeo.

ha silvy
Ik vind dat in het handboek beter beschreven moet worden hoe je zonnepanelen in kaart brengt. 
Er zijn 3 gevallen (voor zover ik kan waarnemen).
•	Een solitair (in weiland of langs de weg)
> 1 punt karteren per solitair (conform objectenhandboek)

•	Geclusterd op daken  op overig bouwerk
> 1 punt karteren per dak van een pand
![zonnepaneel op dak](https://user-images.githubusercontent.com/62252105/219317940-68e43fa1-7dd8-486b-bac0-348fc5cefc69.jpg)

•	Geclusterd in weiland (zonnepark)
> 1 punt karteren voor een zonnepark
> 1 functioneel gebied zonnepark conform contour
> het is inrichtend, dus de ondergrond conform BGT karteren (in voorbeeld BTD > grasland overig)
![zonneakker 2](https://user-images.githubusercontent.com/62252105/219318363-78ab9ce4-ea76-4218-9bcf-961c1926c65a.jpg)

•	Geclusterd in water (zonne-eiland, las ik “on the net”)
(Een zonne-eiland bestaat uit drijvende zonnepanelen die zijn geclusterd tot een drijvend eiland.)
> 1 punt karteren voor een zonnepark
> 1 functioneel gebied zonnepark conform contour
> het is inrichtend, dus de ondergrond conform BGT karteren (in voorbeeld WTD > watervlakte)

![zonne eiland](https://user-images.githubusercontent.com/62252105/219318835-f1cf8c78-cefe-4270-bcc2-1a5ce211fe6b.jpg)

**Comment by SilvyGEONOVUM** [comment]
eens met voorstellen henk-jan

Voorstel:
- voor zonneakker en zonne eiland: functioneel gebied op rh=0, met 4 panelen op hoekpunten (of zoveel al nodig is) en ondergrond BTD of WTD
- voor op daken etc: functioneel gebied op rh=1 met met 4 panelen op hoekpunten (of zoveel al nodig is)

**Comment by adbgnm** [comment]
Ik zou op daken geen functioneel gebied afbakenen. Functionele gebieden zijn macro-objecten in de BGT.
