### ISSUE TITLE
BAG2.0

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#11]

**Comment by SilvyGEONOVUM** [comment]
ook de vraag op welke manier afgebakend moeten worden:
standplaatsen (met verplaatsbare wagens, chalets) in de BAG, die nu vaak als BAG pand met id0000 opgevoerd zijn. Voorstel om af te bakenen als OBW zonder imgeo classificatie

**Comment by adbgnm** [comment]
Opnemen in BAG en BGT bij Pand. 

Standplaatsen en ligplaatsen vormen geen inhoud van de BGT. 
Een woonwagen of woonboot kunnen in IMGeo worden opgenomen als OverigBouwwerk zonder nadere IMGeo classificatie.

**Comment by adbgnm** [comment]
https://github.com/Geonovum/IMGeo-objectenhandboek/commit/9de322a908b1c145ca5bd3f7eb42f328f8c4ce67
