### ISSUE TITLE
galerij

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#13]
nav mail 16-9-22 galerij en trap in de BAG

Zoals je weet was er een verschil in de beschrijving van de pandcontour in BAG en BGT t.a.v. de galerij van een flat. In het objectenhandboek van de BGT stond dat de galerij wel onderdeel uitmaakt van het BAG-pand, maar de klopt niet. Op verzoek van Martijn Klomp van het Kadaster hebben jullie die zinsnede uit het objectenhandboek gehaald.

Maar door het verwijderen ervan is het nu voor de BGT-inwinners niet meer zo duidelijk wat er met galerijen en aangrenzende trappen gedaan moet worden. Ik heb een foto als bijlage meegestuurd. Jullie mogen die in het objectenhandboek gebruiken om deze situatie te verduidelijken.

**Comment by SilvyGEONOVUM** [comment]
#24

**Comment by adbgnm** [comment]
In IMGeo kunnen galerijen van een flat worden opgenomen als Gebouwinstallatie, zonder nadere classificatie.

**Comment by SilvyGEONOVUM** [comment]
**Hoe baken ik galerijen af van een flat, in IMGeo?**
Het advies is om galerijen van een flat op te nemen als Gebouwinstallatie, zonder nadere classificatie.
Voorbeeld: 
![galerijflat](https://user-images.githubusercontent.com/62252105/211837548-e84f2665-e494-4201-8ee5-efa8807f3329.jpg)

**Comment by SilvyGEONOVUM** [comment]
## **Hoe baken ik een galerij en bijbehorende trap af van een flat?**
Een gallerij maakt onderdeel uit van een BAG pand. Bij een BGT pand wordt de galerij juist niet meegenomen, omdat deze niet op rh=0 ligt.
Het advies is om de galerij op te nemen als een objecttype GebouwInstallatie zonder nadere classificatie, op rh > 0.
De toeganstrap wordt opgenomen als een objecttype GebouwInstallatie van het type Toegangstrap.

Voorbeeld

![galerijflat](https://user-images.githubusercontent.com/62252105/216328443-ae8d0cd5-a93a-4c28-b204-2e43a8ca2743.jpg)

In dit voorbeeld zijn er 2 galerijen (objecttype GebouwInstallatie) op rh=1 en rh = 2.

![galerij met trap](https://user-images.githubusercontent.com/62252105/216329170-53f697ff-38a9-454b-9806-ff45e59a2b8d.jpg)

In dit voorbeeld zijn er 2 galerijen (objecttype GebouwInstallatie-zonder classificatie) op rh=1 en rh = 2. De trap is een GebouwInstallatie-toegangstrap, rh = 0.

**Comment by SilvyGEONOVUM** [comment]
foto van galerij is niet correct. Deze galerij is géén BAG onderdeel.
in de FAQs een andere foto gezet en zinnen aangepast.
