### ISSUE TITLE
haagvlakken

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#15]

**Comment by adbgnm** [comment]
Een veelgestelde vraag aan de IMGeo helpdesk is:

Welk object leg ik onder een haag?
Onder een object VegetatieObject van het type 'haag' kan een BegroeidTerreindeel > groenvoorziening worden opgenomen. In eigen beheer kan hier een nadere classificatie (bijvoorbeeld 'haagvak') worden toegevoegd. 

Opnemen in FAQ.

**Comment by SilvyGEONOVUM** [comment]
**Hoe baken ik een haagvak af in de BGT?**
De BGT kent geen specifiek objecttype 'Haagvak'. 
Het advies is om een haag op te nemen en eronder een 'haagvak' te leggen. 
Dit door je door de haag op te nemen als een optioneel objecttype Vegetatieobject (lijn of vlak), van het type Haag. Het haagvlak wordt afgebakend door het opnemen van een verplicht object van het type BegroeidTerreindeel, van het type Groenvoorziening. In de beheeromgeving kan hier een nadere classificatie (bijvoorbeeld 'haagvak') aan worden toegevoegd.
