### ISSUE TITLE
best practice: afbakening kast zonder classificatie

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#18]
vraag: Hoe gaan we om bij de BGT met de post en pakketautomaten van Post NL? Deze worden nu overal geplaatst.
antw: Dit lijkt me een Kast, zonder IMGeo+ classificatie (IMGeo kent dit type kast niet).
_Mocht er een duidelijke behoefte vanuit gebruikers of bronhouders zijn om dit mét classificatie in IMGeo op te nemen dan hoor ik het graag. Dan kunnen we een verbetersuggestie/wijzigingsverzoek op de IMGeo-standaard opnemen in ons meldingensysteem, en dit in een volgende ronde van een nieuwe standaard meenemen._

**Comment by SilvyGEONOVUM** [comment]
**probleem**: er ontbreekt een imgeo classificatie voor bv post- en pakketautomaten.
**analyse**: post- en pakketautomaten zouden geschaard kunnen worden onder een type Kast. De waardenlijst van type Kast is beperkt, deze post- en pakketautomaten staan er niet in.
**![postpakket automaat](https://user-images.githubusercontent.com/62252105/208661239-182f98b2-b2aa-4525-b7d4-184d95de1ccb.JPG)**: Kast is een optioneel objecttype en kan zonder verdere waarde van type Kast afgebakend worden. In een beheerregistratie (BOR) kan aan de Kast een nadere detaillering toegevoegd worden

![postpakket automaat](https://user-images.githubusercontent.com/62252105/208661239-182f98b2-b2aa-4525-b7d4-184d95de1ccb.JPG)

**Comment by SilvyGEONOVUM** [comment]
In het algemeen geldt
**probleem**: als een classificatie ontbreekt voor een van de optionele inrichtingselementen  uit de catalogus (bak, kast, etc.)
![image](https://user-images.githubusercontent.com/62252105/208664589-4cfbe991-aef1-4c66-9d15-96ed65d21e88.png)
**analyse**: hierbij is er altijd de mogelijkheid om *geen* waarde in te vullen bij het attribuut Type.
**afbakening**: noem het betreffende object een van de objecttypes die het beste bij de definitie past en laat attribuut Type leeg.

**Comment by adbgnm** [comment]
**Hoe neem ik objecten op in IMGeo waar geen classificatie voor is?**
Het komt regelmatig voor dat bv een specifiek type kast, of een bepaald type bord als een classificatie ontbreekt in IMGeo. Het betreft vooral de optionele inrichtingselementen uit het optionele deel, zoals bak, bord, kast, etc. In IMGeo mogen objecten zonder nadere classificatie worden opgenomen en aangeleverd aan de LV BGT.

De aanbeveling is om het objecttype te kiezen die het meest past bij de definitie, en het type leeg te laten. In de eigen beheeromgeving kan een nadere classificatie worden opgenomen. Deze kan niet met de LV BGT worden uitgewisseld.
