### ISSUE TITLE
hoofdstuk 4 layout niet correct

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#19]
de tekst in hoofstuk 4 van de BGT catalogus bevat te weinig kopjes op nivo 2. zo moet Positionele nauwkeurigheid  een nivo omhoog, evenals volledigheid, logische consistentie etc.

**Comment by adbgnm** [comment]
Betreft catalogus: Issue verplaatst naar repos IMGeo: https://github.com/Geonovum/IMGeo/issues/23
