### ISSUE TITLE
foto voor OBW opslagtank

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#25]
![thumbnail_mestopslag boerderij](https://user-images.githubusercontent.com/62252105/208947289-0bb07907-6af1-427e-949b-3b113d44d30b.png)
![thumbnail_opslagtanks bij melkfabriek](https://user-images.githubusercontent.com/62252105/208947301-f225a85d-6e89-4386-a42b-b63db254a8f1.png)

**Comment by adbgnm** [comment]
https://github.com/Geonovum/IMGeo-objectenhandboek/commit/4c0c8289448b93e072cdb27201143b53edcd07d2
