### ISSUE TITLE
Opnemen vraag-antwoord verschil tussen bgt:zand en bgt:onverhard&plus:zand

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/IMGeo-objectenhandboek#26]
Wat is het verschil tussen het fysiekvoorkomen 'zand' en 'onverhard:zand' van OnbegroeidTerreindeel?

Het bgt-fysiekvoorkomen 'zand' bij OnbegroeidTerreindeel is bedoeld als zandvlakte, en dat betreft dus strand, strandwallen, en duinen.

Met IMGeo 2.2 wilde we graag het bgt-fysiekvoorkomen 'zand' naar 'zandvlakte' hernoemen maar vanwege de technische impact is dit niet doorgegaan.

OnbegroeidTerreindeel met bgt:onverhard en plus:zand kan worden toegepast voor braakliggende terreinen in stedelijk gebied.

**Comment by SilvyGEONOVUM** [comment]
## **Wat is het verschil tussen een OnbegroeidTerreindeel met fysiekvoorkomen 'zand' en 'onverhard - zand'?**
Het bgt-fysiekvoorkomen 'zand' bij OnbegroeidTerreindeel is bedoeld als zandvlakte, waarmee je dus een strand, strandwallen, en duinen kunt afbakenen.

Voorbeeld

![strand](https://user-images.githubusercontent.com/62252105/216337841-8bbb752d-1c46-47bf-82c2-dd32844c65b6.jpg)

Het OnbegroeidTerreindeel met FysiekVoorkomen Onverhard- en IMgeo de toevoeging Zand, wordt toegepast voor een braakliggende terrein.

Voorbeeld

![vacant-lot-park-grassland-ecosystem-pasture-land-lot-1442455-pxhere com](https://user-images.githubusercontent.com/62252105/216337206-b191e989-904e-4863-871c-db64761fd193.jpg)
