### ISSUE TITLE
Categorietitel binnen categorie Waterdeel

### ISSUE THREAD

**Issue by Oscar-RVO** [Geonovum/IMGeo-objectenhandboek#32]
Boven de beschrijving van greppel/droge sloot staat een categorietitel "OverigBouwwerk" die daar niet thuis lijkt te horen.

**Comment by adbgnm** [comment]
https://github.com/Geonovum/IMGeo-objectenhandboek/commit/9fd2259b4ece8920e474c422e43fa7556389af26
