### ISSUE TITLE
Opnemen afbakening fietsstraat in objectenhandboek

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/IMGeo-objectenhandboek#4]
In het IMGeo objectenhandboek ontbreken voorbeelden en afbakeningsregels voor fietsstraten.

Verzoek is om deze op te nemen in.

**Comment by adbgnm** [comment]
Overweging: middenstuk tussen fietsstroken van fietsstraat als lokale weg of verkeerseiland (scheiding van rijstroken).

**Comment by SilvyGEONOVUM** [comment]
probleem: fietsstraten zijn 
zie [https://www.verkeerskunde.nl/blog/onduidelijkheid-over-fietsstraten](url)
kortom: een fietsstraat is een gewone straat (met 30km zone), aangegeven met een begin en einde bord, met meestal rood asfalt en /of andere inrichting, waar meer fietsers rijden dan auto's en waar de voorrangsregels iets anders zijn dan op een gewone straat.
wat voor de BGT belangrijk is is wat we zien en dat afbakenen. Afhankelijk van de inrichting kan het gaan om andere kleur asfalt, oprijbare verhoging in het midden, extra fietsstroken aan de zijkant, en de borden. Dat betekent dat het niet anders afgebakend wordt dan 2 fietsstroken en een scheiding (dat kan zijn: verhoging, of belijning)

wat is bv het verschil tussen deze:
![image](https://user-images.githubusercontent.com/62252105/208676026-4b7ed8a7-ba8c-4ae1-a604-1dfc4e4bebbf.png)
dit een straat met 3 fietsstroken (normaal)

en deze:
![image](https://user-images.githubusercontent.com/62252105/208676334-d9244e86-9314-41f0-9e56-d6ed13a0c67c.png)
dit is een zgn fietsstraat, maar ik zie hetzelfde. uitgezonderd het bord.

**Comment by adbgnm** [comment]
Opnemen in FAQ

**Comment by adbgnm** [comment]
Hoe baken ik een fietsstraat af in IMGeo?
BGT hanteert als uitgangspunt: dat wat je ziet baken je af. Een fietsstraat is eigenlijk niets anders dan twee fietsstroken met een al dan niet verhoogd middenstuk bedoeld voor verkeer. De fietsstroken worden als Wegdeel > fietspad afgebakend en de middenstrook als Wegdeel met functie lokale weg.

**Comment by SilvyGEONOVUM** [comment]
nav opmerking beoordelingsgroepje:
Maar als de fietsstraat nu geen middengedeelte heeft zoals op onderstaande foto waar een fietspad overgaat in een fietsstraat ? Blijft dit dan rijbaan lokale weg, of is er een andere manier om aan te geven dat dit een fietsstraat is ?
![image](https://user-images.githubusercontent.com/62252105/216595812-1f6044a0-3238-4252-9ffe-e5b768bd3902.png)

In onderstaande situatie kan de middenstrook wel worden gehanteerd door afwisselend vakken asfalt / betonstraatsteen als rijbaan lokale weg vast te leggen.
![image](https://user-images.githubusercontent.com/62252105/216595949-21b2bf52-9e0e-4dcb-a387-2b53ebb10a03.png)

**Comment by adbgnm** [comment]
Als het een fietsstraat is die herkenbaar is aan twee smalle fietsstroken langs de weg en een (hoger) middendeel daartussen, dan is de aanbeveling afbakenen twee fietspaden en strook lokale weg. 

Als dit niet zichtbaar is, dan gaat op het toekennen van een classificatie de hierarchische regel van IMGeo: de domeinwaarde die eerder in de lijst voorkomt prevaleert boven de opvolgende domeinwaarden. In twee bovenstaande voorbeelden is het zowel een fietspad als rijbaan lokale weg. Omdat rijbaan lokale weg hoger in de hierarchie voorkomt, prevaleert deze. Dus bgt-functie 'rijbaan lokale weg'.  De meest ideale oplossing is dubbelfuncties toekennen in IMGeo, of de domeinwaardenlijst uitbreiden (hoewel fietsstraat in NL geen juridische status heeft).

**Comment by SilvyGEONOVUM** [comment]
bij de FAQs verschil gemaakt tussen fietsstraten met en zonder middenberm. Wel zie je dat 99% de fietsstraat een rode kleur gegeven heeft. 
eerst geldt WYSIWYG
daarna geldt de hierarchische regel
