### ISSUE TITLE
best practice terras/vlonder van strandpaviljoen

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#7]
Terrassen/vlonders van de strandpaviljoens worden nu geregistreerd als overbrugging dek (topo niveau 1) daaronder ligt dan strand (topo niveau 0). Deze komen nu als fout in de rapportage omdat er een inrichtend vlak ontbreekt. Bij b.v. een brug zou je een voetpad opnemen op inrichtende laag (niveau 1). Echter het is de vraag of dat hier wel van toepassing is. De vraag is, voldoet de huidige situatie of moet er alsnog een inrichtend vlak opgenomen worden en wat moet dat dan zijn?
 
Soms wordt er een pand in de BAG van gemaakt. Als je het volgens de definities bekijkt, dan is een strandpaviljoen voor de BAG helemaal geen pand, tenminste  als het iedere winter wordt opgeruimd dan is het niet duurzaam verbonden….

Als je een strandpaviljoen toch een BAG pand vindt (er zit rekbaarheid in de definitie mbt ‘duurzaam verbonden”…)..., dan zou het wel het beste zijn om de afbakening van het BAG pand (van boven) en die van het BGT pand (maaiveld) nagenoeg gelijk te laten zijn. In de BGT wordt het omliggende terras niet bij het overig bouwwerk/pand getrokken, immers, dat maakt geen onderdeel uit van het pand. Een gebouwinstallatie-bordes of een onbegroeid terreindeel (eventueel erf of open verharding) is dan het beste.

Een standplaats (ipv pand) zou voor de BAG hier veel logischer en correcter zijn. Nml volgens catalogus: “In dit onderdeel wordt een definitie van het begrip standplaats voorgesteld. Daaronder wordt verstaan de locatie waar met panden vergelijkbare bouwwerken permanent of semi-permanent kunnen worden geplaatst. Hierbij kan onder meer worden gedacht aan woonwagens en strandpaviljoens.” Echter een standplaats kun je niet in de BGT afbakenen. Maar het pand kun je dan weer wel als een overig bouwwerk opnemen (zonder detailclassificatie). Ook dan kan weer: In de BGT wordt het omliggende terras niet bij het overig bouwwerk/pand getrokken, immers, dat maakt geen onderdeel uit van het pand. Een gebouwinstallatie-bordes is dan het meest correcte. Een onbegroeid terreindeel (eventueel erf of open verharding) is ook nog te verdedigen.

kortom:

**Comment by SilvyGEONOVUM** [comment]
**probleem**: terrassen / vlonders bij strandpaviljoens worden niet eenduidig afgebakend. in feite zijn het 2 vragen: hoe een strandpaviljoen af te bakenen? en hoe het terras / vlonder af te bakenen?
**analyse**: afbakening van het paviljoen zelf (dus zonder het omliggende terras), is afhankelijk van de regels voor de BAG. Dat wil zeggen: het is ofwel een BAG pand (en dus een BGT pand) ofwel geen BAG pand (en dus een OverigBouwwerk voor de BGT).  _Daarmee zou het attribuut TypeOverigBouwwerk wel ingevuld moeten worden, want dat is een verplicht attribuut. Echter strandpaviljoen kun je niet selecteren als waarde van dit attribuut. ... _

**Comment by adbgnm** [comment]
Toevoegen aan BAG en BGT bij Pand.

**Comment by adbgnm** [comment]
**Hoe baken ik strandpaviljoens met terras/vlonder af in de BGT?**
Of een strandpaviljoen wordt afgebakend als Pand is afhankelijk van de regels voor de BAG. 
Als het strandpaviljoen is opgenomen in de BAG, dan is dit object opgenomen als Pand in de BGT.
Als het strandpaviljoen niet is opgenomen in de BAG, dan mag het object opgenomen worden als OverigBouwwerk zonder nadere classificatie in IMGeo.
De aanbeveling is om het Pand of OverigBouwwerk op relatieve hoogte 1 in de BGT of IMGeo op te nemen omdat het meestal op palen rust.

Het omliggende terras/vlonder maakt geen onderdeel uit van de geometrie van het Pand of OverigBouwwerk. De aanbeveling is om het terras/vlonder als OnbegroeidTerreindeel met fysiekvoorkomen 'open verharding' op relatieve hoogte 1 op te nemen in IMGeo. Het strand loopt er als Onbegroeidterreindeel 'strand' onder door op relatieve hoogte 0.
Strandpaviljoens vormen ge
