### ISSUE TITLE
best practice houten bruggetjes

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#8]
**Hoe moet ik een houten wandel/fietsbrug afbakenen en welk fysiekvoorkomen krijgt het wegdeel +1 (gesloten verharding/ openverharding en hoe verder te verbijzonderen in het kader van IMGEO)?** 
Hierover is al eerder een vraag gesteld aan Geonovum. 

Volgens de kwaliteitsrapportage BGT van het Kadaster geldt: Een overbruggingsdeel op niveau 1 (en hoger) zou in de regel voorzien moeten zijn van een bovenliggend object (WGD, OWG, BTD, OTD, OWT, WTD). Overbruggingsdelen die niet aan wegdelen op niveau 0 grenzen zijn buiten beschouwing gelaten.
Aanvullende stelt Geonovum: De consistentieregel is nergens in IMGeo vastgelegd. Dus eigenlijk niet normatief. Als voorbeeld: Hoe ga je om met langlopende infrastructurele werken waarbij de pijlers (ook overbruggingsdeel) misschien wel jaren in het terrein aanwezig zijn, zonder dat er een dek op ligt, en dus een weg op ligt?

Volgens Geonovum geldt: 
In de BGT leggen we geen fysiekvoorkomen (materiaal) bij het object overbruggingsdeel vast. 
Een houten brug kan in de BGT als overbruggingsdeel met in IMGeo+ TypeOverbrugging:brug worden opgenomen.

In IMGeo heeft een brug geen fysiekvoorkomen; een wegdeel wel. Een wegdeel op een overbrugging heeft dus een fysiekvoorkomen. Een houten brug met een voetpad van hout wordt in de BGT opgenomen als open verharding (hout = elementenverharding = open verharding).

M.b.t. een brug van hout met daarover een voetpad van hout. Het advies is dan om een wegdeel met fysiekvoorkomen ‘open verharding’ (cf. eisen aan de inhoud voor het samenhangend stelsel van geobasisgegevens ofwel DiS-Geo/SOR) op het overbruggingsdeel op te nemen in de BGT.

**Comment by SilvyGEONOVUM** [comment]
**probleem**: Hout is geen waarde die voorkomt als waarde van het attribuut FysiekVoorkomenPlusXX, bv bij een weg of een onbegroeid terreindeel. 
**analyse**: Specifiek voor bruggetjes die geheel van hout zijn, is het ontbreken van deze waarde een gemis.
**afbakening**: Een houten brug met een voetpad van hout wordt in de BGT opgenomen als 
_overbruggingsdeel (verplicht) 
met een typeOverbrugging = Brug, 
en typeOverbruggingsdeel = dek, waarvan het fysiekVoorkomen attribuut de aarde open verharding (hout = elementenverharding = open verharding) heeft._

**Comment by adbgnm** [comment]
Toevoegen in FAQ + voorbeeldfoto opnemen bij Wegdeel > fysiekvoorkomen > open verharding

**Comment by adbgnm** [comment]
**Hoe neem ik houten fiets- of voetbruggetjes op in de BGT?**
De brug wordt als Overbruggingsdeel met typeOverbrugging 'brug' en typeOverbruggingsdeel 'dek' opgenomen op een relatieve hoogte groter dan 0. Op het overbruggingsdeel wordt het voet- of fietspad opgenomen in de BGT als Wegdeel met fysiekvoorkomen 'open verharding' op dezelfde relatieve hoogte.
