### ISSUE TITLE
best practice: hoe moet ik een oplaadpaal afbakenen?

### ISSUE THREAD

**Issue by SilvyGEONOVUM** [Geonovum/IMGeo-objectenhandboek#9]
**De oplaadpaal voor elektrische voertuigen ontbreekt in het model?** 
Voor dit punt verwijzen we naar IMBOR waar een laadpunt gedefinieerd is als: Een regeltoestel voor het laden van elektrische voertuigen welke geïntegreerd is in een lichtmast, op een paal bevestigd is of in of op of aan een ander object bevestigd is. 
M.a.w. een laadpaal/punt zou in de BOR registratie opgenomen moeten worden.

in IMGEO (optioneel) kun je een oplaadpaal, als een type paal opnemen, zonder verdere optionele type aanduiding.

**Comment by SilvyGEONOVUM** [comment]
[#18 ](url)

**Comment by SilvyGEONOVUM** [comment]
**probleem**: laadpalen voor electrische auto's zijn geen aparte

**Comment by adbgnm** [comment]
Voorstel: Laadpaal is een installatie, vergelijkbaar met zonnepaneel?

**Comment by adbgnm** [comment]
**Hoe moet ik een oplaadpaal opnemen in IMGeo?**
IMGeo heeft geen eigen classificatie voor een laadpaal. De aanbeveling is om een laadpaal als objecttype Paal zonder nadere classificatie op te nemen.
